### ISSUE TITLE
Update repo to match the version in app stores

### ISSUE THREAD

**Issue by PaperMonster** [codeforpublic/morchana-app#46]
The source code of this repo is older than the current version on app stores. It would be nice to keep them synced to ensure transparency, less misunderstandings, and ease of community contribution.

**Comment by chrisza4** [comment]
Agree. I want to contribute but I am quite unsure if contributing to this repo going to yield any value.

Can we have a confirmation if this repo is up-to-date?

**Comment by bact** [comment]
There's another fork here, but also not that up-to-date.
https://github.com/Morchana/morchana-app

**Comment by PaperMonster** [comment]
As #52 has been merged, I'm closing this. Kudos to the collaborators!
