### ISSUE TITLE
ระบบรองรับ Beacon หรือยังครับ ?

### ISSUE THREAD

**Issue by songwutk** [codeforpublic/morchana-app#50]
ช่อง Youtube อาจารย์ลอยได้พูดถึงการใช้ Beacon ไว้
(https://www.youtube.com/post/Ugx-a-Lv7RWQ-ILPteJ4AaABCQ?ocd=1)

ถ้าสนใจอยากทดลองทำ Beacon ไว้ติดตี้งในสถานประกอบการ จะศึกษาได้จากไหน 
สามารถดัดแปลงจาก ESP32 แบบของไลน์ได้หรือไม่ ?

(https://medium.com/@benz20003/%E0%B8%AD%E0%B8%A2%E0%B8%B2%E0%B8%81%E0%B8%97%E0%B8%B3-beacon-%E0%B8%95%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%A5%E0%B8%AD%E0%B8%87-line-beacon-%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2-esp32-4fc801315409)

**Comment by lifnaja** [comment]
ตอนนี้ lib ที่พี่ๆ เขียน "react-native-contact-tracer": "git://github.com/Morchana/contact-tracer.git",    detect beacon ได้ละครับ 

อันนี้ฝั่ง mobile ที่รับของมาจาก native ครับ https://github.com/codeforpublic/morchana-app/blob/master/src/services/contact-tracing-provider.tsx
